### PR TITLE
Fix #1150

### LINKED ISSUE #1150: offmol.assign_fractional_bond_orders fails with default kwargs
**Describe the bug**

```python
from openff.toolkit.topology import Molecule
offmol = Molecule.from_smiles('CCO')
offmol.assign_fractional_bond_orders()
```

yields

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9112d4c076cb> in <module>
      1 from openff.toolkit.topology import Molecule
      2 offmol = Molecule.from_smiles('CCO')
----> 3 offmol.assign_fractional_bond_orders()

~/projects/OpenForceField/openff-toolkit/openff/toolkit/topology/molecule.py in assign_fractional_bond_orders(self, bond_order_model, toolkit_registry, use_conformers)
   3539 
   3540         """
-> 3541         bond_order_model = bond_order_model.lower()
   3542 
   3543         if isinstance(toolkit_registry, ToolkitRegistry):

AttributeError: 'NoneType' object has no attribute 'lower'
```

The casual observer might think that the issue was caused by https://github.com/openforcefield/openff-toolkit/pull/1031, but it was actually always there. #1031 was just a code cleanup that uncovered it. 

**Computing environment (please complete the following information):**
 - Mac OSX 12
 - OFFTK 0.10.1

**Additional context**

### PR DESCRIPTION
**Pull request by j-wags**
- [x] Fixes #1150 by not lowercasing `bond_order_model` in `Molecule.assign_fractional_bond_orders`. Note that both `OpenEyeToolkitWrapper.assign_fractional_bond_orders` and `AmberToolsToolkitWrapper.assign_fractional_bond_orders` explicitly change `None` to `am1-wiberg` and perform lowercasing internally, so lowercasing the argument in `Molecule.assign_fractional_bond_orders` is redundant. 
- [x] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [x] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Review by mattwthompson — APPROVED** [review]
LGTM - I do think the issue was introduced [here](https://github.com/openforcefield/openff-toolkit/pull/1031/files#diff-68cb3f9873e00994ccf957cc089b18cbaf34302d5eeb90c34ca289803e10a69eR3522-R3523) but a more alarming concern is that `mol.assign_fractional_bond_orders()` was never in the test suite.

**Comment by j-wags** [comment]
Thanks, @mattwthompson!
