### ISSUE TITLE
offmol.assign_fractional_bond_orders fails with default kwargs

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#1150]
**Describe the bug**

```python
from openff.toolkit.topology import Molecule
offmol = Molecule.from_smiles('CCO')
offmol.assign_fractional_bond_orders()
```

yields

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9112d4c076cb> in <module>
      1 from openff.toolkit.topology import Molecule
      2 offmol = Molecule.from_smiles('CCO')
----> 3 offmol.assign_fractional_bond_orders()

~/projects/OpenForceField/openff-toolkit/openff/toolkit/topology/molecule.py in assign_fractional_bond_orders(self, bond_order_model, toolkit_registry, use_conformers)
   3539 
   3540         """
-> 3541         bond_order_model = bond_order_model.lower()
   3542 
   3543         if isinstance(toolkit_registry, ToolkitRegistry):

AttributeError: 'NoneType' object has no attribute 'lower'
```

The casual observer might think that the issue was caused by https://github.com/openforcefield/openff-toolkit/pull/1031, but it was actually always there. #1031 was just a code cleanup that uncovered it. 

**Computing environment (please complete the following information):**
 - Mac OSX 12
 - OFFTK 0.10.1

**Additional context**
