### ISSUE TITLE
assign_partial_charges() fails

### ISSUE THREAD

**Issue by pavankum** [openforcefield/openff-toolkit#821]
**Describe the bug**
I was trying to run forcebalance with the new toolkit version and assign_partial_charges() has a new line `_cls=self.__class__` in the `toolkit_registry.call()` here https://github.com/openforcefield/openff-toolkit/blob/master/openff/toolkit/topology/molecule.py#L2871-L2884, which raises an issue with the toolkits during openmm system creation. This doesn't seem to be a problem when a molecule is created from smiles and a call is made to compute the partial charges but somehow causing issues in a forcebalance run.

**To Reproduce**
Attached a sample forcebalance input for a single molecule and conda env used.
[git_issue_report.tar.gz](https://github.com/openforcefield/openff-toolkit/files/5843708/git_issue_report.tar.gz)

**Output**
/data/homezvol1/pbehara/.conda/envs/fb_trial_env/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py:4176: Warning: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name '' and SMILES '[H]c1c(c(c(c(c1[H])c2c(c(c(c(n2)[H])[H])[H])[H])N(C([H])([H])[H])C([H])([H])[H])[H])[H]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, '_cls': <class 'openforcefield.topology.molecule.FrozenMolecule'>}"
Available toolkits are: [ToolkitWrapper around OpenEye Toolkit version 2020.2.0, ToolkitWrapper around The RDKit version 2020.09.3, ToolkitWrapper around AmberTools version 20.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around OpenEye Toolkit version 2020.2.0 <class 'TypeError'> : oe_cached_assign_partial_charges() got an unexpected keyword argument '_cls'
 ToolkitWrapper around The RDKit version 2020.09.3 <class 'openforcefield.utils.toolkits.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94']
 ToolkitWrapper around AmberTools version 20.0 <class 'TypeError'> : at_cached_assign_partial_charges() got an unexpected keyword argument '_cls'
 ToolkitWrapper around Built-in Toolkit version None <class 'openforcefield.utils.toolkits.ChargeMethodUnavailableError'> : Partial charge method "am1bcc"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']

  warnings.warn(str(e), Warning)

**Computing environment (please complete the following information):**
 - conda-env.yml in the attached folder

**Additional context**
Works fine with earlier versions of toolkit (0.8.0).

**Comment by mattwthompson** [comment]
Is this the same issue as https://github.com/leeping/forcebalance/issues/193? If I recall correctly, the temporary workaround is to downgrade to 0.8.0 and the proper solution is in place (particularly once we bring CI back online)

**Comment by pavankum** [comment]
Thanks @mattwthompson , yeah same thing, sorry for double posting, I missed the previous report, would have saved me a day or two.
